minimum_pre_commit_version: 3.0.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
        files: (?!.*3rd-party)^.*$ # ignore 3rd-party files
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf'] # fix line endings to unix style
        files: (?!.*3rd-party)^.*$ # ignore 3rd-party files
    -   id: check-case-conflict
    -   id: check-json
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: clang-format-with-version-check
        name: clang-format
        description: Format files with ClangFormat.
        entry: bash ./scripts/clang_format.hook -i
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|cuh|hpp|hxx|proto)$

- repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
  rev: v0.6.9
  hooks:
    - id: cmake-format
